build:
    environment:
        php:
            version: 7.3
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=/tmp/coverage-clover.xml'
                coverage:
                    file: '/tmp/coverage-clover.xml'
                    format: 'clover'